### PR TITLE
Fix profile block for templates.

### LINKED ISSUE #85: Author option shows template author for single post template.
When editing a template via the site editor the Author option of the Gravatar Profile block refers to the template's author.

In the case of the "Single Posts" template, it's easy to expect that the Author option should be referring to the post itself, and not the template.

Similarly we would expect the same for the "Single Page".

Maybe for the non-page and non-post templates we should remove the Author option? Doesn't seem like the template author is any useful.

### PR DESCRIPTION
**Pull request by aaronfc**
Fixes #85 

## Description
- Reworked the way we calculate the author email by using context's `postId` and `postType`.

## Testing instructions
- [ ] Check code.
- Checkout to branch.
- Add a Profile Block in a post and test:
  - [ ] Author option works as expected (post's author).
  - [ ] User option works as expected (selected user).
  - [ ] Custom email option works as expected.
  - [ ] Confirm each of the above are correctly displayed in the post view (not the editor).
- [ ] Repeat above tests with a Page.
- Go to site editor and edit the "Single Post" or "Page" templates.
- [ ] Confirm Author option works as expected in the editor.
- [ ] Confirm option works as expected in the final view.

### Editor view

image

image

image

image

image

### Post public view

gravatar-enhanced local_8-2_

### Author in Single Post template

image

### CODE REVIEW

**Review by wellyshen — COMMENTED** [review]
Maybe I have missed some context. Regarding this issue, [I plan to hide the "Author" option and set the default to "User" so that the editor can select the user they want to display](https://github.com/Automattic/gravatar-enhanced/blob/trunk/src/block/edit.tsx#L105). This approach avoids the inconsistent profile display between the editor and the frontend, resulting in a better user experience

https://github.com/user-attachments/assets/62afdf3a-2aee-45a5-a288-2ee64f5f438e

However, I've noticed a race condition bug that causes unexpected results. We can fix the bug by updating [this hook](https://github.com/Automattic/gravatar-enhanced/blob/trunk/src/block/edit.tsx#L106-L117) to:

```tsx
	useEffect( () => {
		if ( userType === UserTypes.EMAIL || userEmail ) {
			return;
		}

		// When first time to edit a template, the `authorEmail` is not available. Use the first user's email as a fallback.
		if ( userType === UserTypes.AUTHOR && authorEmail ) {
			setAttributes( { userEmail: authorEmail } );
		} else if ( firstUserEmail ) {
			setAttributes( { userType: UserTypes.USER, userEmail: firstUserEmail } );
		}
	}, [ authorEmail, firstUserEmail, setAttributes, userEmail, userType ] );
```

Please note: The above fixing also simplifies the code a little bit by removing:

```
const isEditingTemplate = useSelect( ( select: SelectFn ) => select( 'core/edit-site' )?.isPage() === false, [] );
```

**Comment by aaronfc** [comment]
I will look into the race condition. Thanks!

> Maybe I have missed some context. Regarding this issue, [I plan to hide the "Author" option and set the default to "User" so that the editor can select the user they want to display](https://github.com/Automattic/gravatar-enhanced/blob/trunk/src/block/edit.tsx#L105). This approach avoids the inconsistent profile display between the editor and the frontend, resulting in a better user experience

Yes, the thing is that we want to have the _Author_ option, that means the author of the page or post will be shown. If we have to select a user manually from the site editor, it will always show that user. But in templates it makes sense to show the real post or page author.

Happy to talk about it in DM if you prefer.

**Comment by wellyshen** [comment]
> Yes, the thing is that we want to have the _Author_ option, that means the author of the page or post will be shown. If we have to select a user manually from the site editor, it will always show that user. But in templates it makes sense to show the real post or page author.

~~I agree, but I'm somewhat concerned about the inconsistent profile display between the editor and the frontend view, which feels unintuitive from a UX perspective.~~

~~The current approach for the profile creation is:~~

~~- 1st time editing a template: No the author email, hide the "Author" option and use the "User" option instead~~
~~- After 1st time editing: Has the author email, using the "Author" option as the default~~

~~You can apply [this fixing (and code simplifying)](https://github.com/Automattic/gravatar-enhanced/pull/88#pullrequestreview-2725320229) to see if the UX is OK.~~

~~BTW, if you are OK with the approach. I can fix the race condition bug (and code simplifying) and do comprehensive testing.~~

@aaronfc After I thought twice. From the POV of a template. I think your approach makes sense. I will review the code and test the block in different cases, thanks bro!

File: src/block/edit.tsx [hunk 1]
```diff
@@ -60,16 +60,19 @@ export default function Edit( { attributes, setAttributes, clientId }: Props ) {
...
 
-	const authorEmail = useSelect( ( select: SelectFn ) => {
-		const postType = select( 'core/editor' ).getCurrentPostType();
-		const postId = select( 'core/editor' ).getCurrentPostId();
-		const authorId = select( 'core' ).getEntityRecord( 'postType', postType, postId )?.author;
+	// Get author email from postType and postId in the context.
+	const authorEmail = useSelect(
+		( select: SelectFn ) => {
+			const { getEditedEntityRecord, getEntityRecord } = select( 'core' );
+			const _authorId = getEditedEntityRecord( 'postType', postType, postId )?.author;
```
Comment (wellyshen) [inline src/block/edit.tsx]: Does `_authorId` signify a private variable? We don't use it in the profile block. Moreover, `_authorId` is available only within the function's scope, so I recommend using `authorId` directly.

> Note: Re the `_debounce`, which represents [the lodash debounce](https://www.lodashjs.com/docs/lodash.debounce/#_debouncefunc-wait0-options)

**Review by wellyshen — APPROVED** [review]
Tested as described and the code LGTM, great work 💯. I have left a comment, please take a look 👀
